package Dominio;

/**
 *
 * @author Arthur
 */
public enum TipoToken{
    IDENTIFICADOR, VAR, INICIO, FIMALGORITMO, SEPARADOR, OPERADOR, LITERAL, NUMERO, COMENTARIO, PALAVRA_RESERVA, INTEIRO, LOGICO, REAL;
}
